### ISSUE TITLE
Integration Test

### ISSUE THREAD

**Issue by paula810** [AuScope/portal-core#180]
Hello,

Can you please point me exactly to your integration test file.

Pallavi

**Comment by joshvote** [comment]
Hi Pallavi,

We have a public travis instance with unit test status at https://travis-ci.org/AuScope/portal-core . We also have a non public Jenkins instance with more detailed results of our unit tests. What specifically were you after?

**Comment by paula810** [comment]
Shouldn't the project have some integration tests considering that you are working with Openstack NOVA, so ideally you would whether the whole environment is working fine. I wanted the link to that.

**Comment by victortey** [comment]
Hi, not sure if you have the right repository but can we confirm what would you like to get out of portal-core. AFAIK, the underlying framework utilize jcloud for cloud interaction and our integration testing are limited  to our local architecture. Anything test involving external service such as cloud compute are mocked using jcloud
